name: Scrape and Notify

on:
  # Triggers the workflow every 5 minutes
  schedule:
    - cron: "*/1 * * * *"

jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: volta-cli/action@v3
      - run: yarn install
      - run: yarn start
