name: Scrape and Notify

on:
  # Triggers the workflow every 5 minutes
  schedule:
    - cron: '*/1 * * * *'

jobs:
  # This workflow contains a single job called "cron"
  cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup volta, node and yarn
        uses: volta-cli/action@v3
      - name: Install dependencies
        run: yarn install

      - name: Download previous state artifact
        uses: actions/download-artifact@v3
        with:
          name: previous-state

      - name: Run the script

        env:
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}

          CALENDAR_URL: ${{ secrets.CALENDAR_URL }}

          CALENDAR_OWNER: ${{ secrets.CALENDAR_OWNER }}
          CALENDAR_ID: ${{ secrets.CALENDAR_ID }}

          APPOINTMENT_TYPE: ${{ secrets.APPOINTMENT_TYPE }}

        run: yarn start

      - name: Upload previous state artifact
        uses: actions/download-artifact@v3
        with:
          name: previous-state
          path: PREVIOUS_STATE.json
          retention-days: 7
