name: Scrape and Notify

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/31 * * * *'

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Load state
        uses: jorgebg/stateful-action@v0.1

      - name: Setup volta, node and yarn
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Run the script

        env:
          PUSHOVER_USER: ${{ secrets.PUSHOVER_USER }}
          PUSHOVER_TOKEN: ${{ secrets.PUSHOVER_TOKEN }}

          CALENDAR_URL: ${{ secrets.CALENDAR_URL }}

          CALENDAR_OWNER: ${{ secrets.CALENDAR_OWNER }}
          CALENDAR_ID: ${{ secrets.CALENDAR_ID }}

          APPOINTMENT_TYPE: ${{ secrets.APPOINTMENT_TYPE }}

          STATE_FILE: '.state/PREVIOUS_AVAILABILITY.json'

        run: yarn start
